default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: patoinformatico
  host: localhost

development:
  <<: *default
  database: howarts_rails_development

test:
  <<: *default
  database: howarts_rails_test

production:
  <<: *default
  # En producciÃ³n, Render utiliza DATABASE_URL
  url: <%= ENV['DATABASE_URL'] %>
